// <auto-generated />
using System;
using Cashicart.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cashicart.Infrastructure.Migrations
{
    [DbContext(typeof(CashicartDbContext))]
    [Migration("20250623122734_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cashicart.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            AuditLogId = new Guid("0557db3f-aa36-4320-93c2-e931ea64929f"),
                            Action = "CreateProduct",
                            CreatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8552),
                            EntityId = new Guid("77777777-7777-7777-7777-777777777777"),
                            EntityName = "Product",
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("8482d5ce-a8be-4510-beaa-b3dfa511fff3"),
                            CreatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8414),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Phone = "123-456-7890"
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("InventoryAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InventoryAdjustmentId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryAdjustments");

                    b.HasData(
                        new
                        {
                            InventoryAdjustmentId = new Guid("c3f72397-b379-4a40-b6d7-ddf9eff11371"),
                            CreatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8525),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 5,
                            Reason = "Restock",
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("503eb665-a4cb-40f2-88bb-61f0c3302fc1"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8177),
                            Name = "Laptop",
                            Price = 999.99m,
                            SKU = "LAP001",
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8178)
                        },
                        new
                        {
                            ProductId = new Guid("c9e50e13-e446-4b3c-a7b5-912ec3a38903"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8188),
                            Name = "Phone",
                            Price = 499.99m,
                            SKU = "PHN001",
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2025, 6, 23, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8188)
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.TransactionItem", b =>
                {
                    b.Property<Guid>("TransactionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");

                    b.HasData(
                        new
                        {
                            TransactionItemId = new Guid("557231c2-2069-46f1-b392-eac6ba0c35d1"),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 1,
                            TransactionId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            TransactionItemId = new Guid("3b6cc23b-0b0d-40bb-8283-6dc9185540f6"),
                            ProductId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Quantity = 1,
                            TransactionId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UnitPrice = 499.99m
                        });
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 6, 22, 12, 27, 33, 623, DateTimeKind.Utc).AddTicks(8439),
                            Status = 1,
                            TotalAmount = 1499.98m,
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.TransactionItem", b =>
                {
                    b.HasOne("Transaction", null)
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
