// <auto-generated />
using System;
using Cashicart.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cashicart.Infrastructure.Migrations
{
    [DbContext(typeof(CashicartDbContext))]
    [Migration("20250701145559_AddOrderTables")]
    partial class AddOrderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cashicart.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            AuditLogId = new Guid("8c83bb18-1305-4dab-b2b6-f09ef87ed034"),
                            Action = "CreateProduct",
                            CreatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(617),
                            EntityId = new Guid("77777777-7777-7777-7777-777777777777"),
                            EntityName = "Product",
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("a527a394-9175-4109-a8f2-45c73b32cded"),
                            CreatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(484),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Phone = "123-456-7890"
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("InventoryAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InventoryAdjustmentId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryAdjustments");

                    b.HasData(
                        new
                        {
                            InventoryAdjustmentId = new Guid("f3aee17c-5f96-445b-9ede-cbb37fec0cd6"),
                            CreatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(585),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 5,
                            Reason = "Restock",
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("ae405f2a-3dc0-4176-8afd-04b032ae36bd"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(257),
                            Name = "Laptop",
                            Price = 999.99m,
                            SKU = "LAP001",
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(258)
                        },
                        new
                        {
                            ProductId = new Guid("91a54551-41fa-4bda-a7f9-522e2e9c7393"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(278),
                            Name = "Phone",
                            Price = 499.99m,
                            SKU = "PHN001",
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2025, 7, 1, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(279)
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.TransactionItem", b =>
                {
                    b.Property<Guid>("TransactionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");

                    b.HasData(
                        new
                        {
                            TransactionItemId = new Guid("32a95d15-7777-4870-944f-9e5adb89ee66"),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 1,
                            TransactionId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            TransactionItemId = new Guid("85ad40dd-df64-4ef6-9a2e-8f0fd4e6a77d"),
                            ProductId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Quantity = 1,
                            TransactionId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UnitPrice = 499.99m
                        });
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 6, 30, 14, 55, 59, 139, DateTimeKind.Utc).AddTicks(513),
                            Status = 1,
                            TotalAmount = 1499.98m,
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Cashicart.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.TransactionItem", b =>
                {
                    b.HasOne("Transaction", null)
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cashicart.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
